In [1]:
from epymetheus import Trade
from epymetheus.datasets import make_randomwalk

import numpy as np

/usr/local/lib/python3.7/site-packages/pandas_datareader/compat/__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal

In [2]:
universe = make_randomwalk()
universe.prices

,0,1,2,3,4,5,6,7,8,9
0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,1.007681,1.008622,0.986874,1.004338,0.998096,0.989420,1.025786,0.986699,0.998385,1.010474
2,0.988404,1.008224,0.997989,0.997230,0.996584,0.982855,1.021509,0.981379,0.997742,0.996891
3,1.002785,1.015039,0.988128,1.003776,1.007543,0.983854,1.022166,0.995717,1.005106,0.998146
4,1.019577,1.007689,0.999245,1.002840,1.018351,0.989438,1.026495,1.012665,0.997203,0.991239
...,...,...,...,...,...,...,...,...,...,...
995,1.150596,1.007651,0.915249,1.090203,0.851387,1.360347,1.358341,1.645201,0.998320,0.925446
996,1.153912,1.026708,0.913223,1.067939,0.841650,1.362067,1.364252,1.616639,0.997408,0.938578
997,1.151019,1.027974,0.914268,1.072002,0.848784,1.354864,1.336385,1.624055,1.014084,0.945212
998,1.151384,1.036293,0.897989,1.057280,0.849070,1.363835,1.353077,1.623503,1.019161,0.944050
999,1.160648,1.034870,0.908484,1.066814,0.871846,1.356242,1.364699,1.626633,1.013302,0.926196

In [3]:
trade = Trade('0', open_bar=2, shut_bar=5)

trade.execute(universe)

# i = universe.get_asset_indexer('0').reshape(-1)
# i
# universe.get_asset_indexer(['0', '2'])
# universe.prices.iloc[:, np.array(0)]